// Request for testing directly the movies API

@hmovies-api-domain=localhost
@hmovies-api-port=7172
@api-key=68e5fbda-9ec9-4858-97b2-4a8349764c63
@existent-movie-ID=ID-test1
@inexistent-movie-ID=ID-test2

###

GET http://{{http-movies-api-domain}}:{{http-movies-api-port}}/v1/movies
X-Apikey:{{api-key}}

###

GET http://{{http-movies-api-domain}}:{{http-movies-api-port}}/v1/movies/{{existent-movie-ID}}
X-Apikey:{{api-key}}

###

GET http://{{http-movies-api-domain}}:{{http-movies-api-port}}/v1/movies/{{inexistent-movie-ID}}
X-Apikey:{{api-key}}
